### ISSUE TITLE
Natura Mod Duplication

### ISSUE THREAD

**Issue by OfficialZygorg** [DrParadox7/Lost-Era-Modpack#1]
As the modpack inicialises, the mod natura-1-7.10-2.4.2-dev.jar forms into natura-1-7.10-2.4.2-dev-patched.jar but not deleting the non patched mod, causing the modpack inicialization to fail.

My temp fix is deleting the non patched natura as it loads.

Also, it will auto download if the non patched version is deleted (when starting the modpack again)

**Comment by DrParadox7** [comment]
Thanks for the report. That has now been fixed in the latest hotfix version
