### ISSUE TITLE
Extremely low TPS when in certain naturally generated areas

### ISSUE THREAD

**Issue by CJCWIS** [DrParadox7/Lost-Era-Modpack#102]
### Your Pack Version

1.6.5a

### Type of Instance

Multiplayer

### Your Expectation

I expect that when I explore freshly generated chunks that I don't get a certain area where it gets to about 8 TPS or lower.

### The Reality

Server log: [2024-05-27-1.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/15462891/2024-05-27-1.log)
FML Server log: [fml-server-3.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/15462613/fml-server-3.log)
Results from using vanilla debug profiler for around a minute: [profile-results-2024-05-27_19.27.27.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/15462608/profile-results-2024-05-27_19.27.27.txt)

On seed "4947242236526689109", around coordinates x:620 y:81 z:352, the TPS drops significantly (this happens in both singleplayer and multiplayer). This significant TPS lag has happened to me on another seed as well, however I no longer have the save. This issue only persists when the affected area is loaded. Edit: I am using the Realistic world type.

Screenshot of the affected area of the world sitting idle with low TPS: ![lowtps](https://github.com/DrParadox7/Lost-Era-Modpack/assets/23131218/98abb9b9-4344-4089-a812-bf51ba1f328a)

I have only just started the modpack around a week ago (playing sporadically), and have encountered this issue twice. If you were to load a new world you probably would be able to find an area where this happens relatively quickly (for convenience though, just use the provided world seed and coordinates).

Screenshot of world spawn with normal TPS: ![normaltps](https://github.com/DrParadox7/Lost-Era-Modpack/assets/23131218/f05c6df8-29c1-4751-bf26-cfafba73977e)

### Your Proposal

Identify what is causing the problem and either fix it or report it to the mod's author (if it is a mod causing the issue). I apologize I could not do this myself, I just simply do not know how to properly identify what is causing the major TPS lag.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
You can solve this in 1 of 2 ways:
- Update [Hodgepodge](https://modrinth.com/mod/hodgepodge/versions) server side
- set `B:FasterLeaveDecay` to `false` in `.minecraft/config/RandomThings.cfg`

I'll try to get an update shortly to fix this among other things

**Comment by DrParadox7** [comment]
Fixed in 1.6.6
