### ISSUE TITLE
Red Alloy Ingot -> Red Alloy Plate, Hardened Flux Capacitor

### ISSUE THREAD

**Issue by hatalmasalma** [DrParadox7/Lost-Era-Modpack#105]
Modpack 1.6.7

- All GregTech machines only accept GregTech Red Alloy Ingot for making Red Alloy Plates, don't accept the one from ProjectRed.

- Thermal Expansion Hardened Flux Capacitor recipe only accepts ProjectRed Red Alloy Ingot, doesn't accept the one from Gregtech.

**Comment by DrParadox7** [comment]
> All GregTech machines only accept GregTech Red Alloy Ingot for making Red Alloy Plates, don't accept the one from ProjectRed.
Intentionally designed by GT4

> Thermal Expansion Hardened Flux Capacitor recipe only accepts ProjectRed Red Alloy Ingot, doesn't accept the one from Gregtech.
Fixed
