### ISSUE TITLE
Saving Bug?

### ISSUE THREAD

**Issue by Soulstealer86** [DrParadox7/Lost-Era-Modpack#106]
### Your Pack Version

1.6.7

### Type of Instance

Single Player

### Your Expectation

I load into the game a while after exiting and saving (when I run errands or need to put my computer in sleep mode or something), and I expect to be where I left off, with my inventory and the world's inventory as I left it.

### The Reality

The game puts me at a point where I wasn't when I'd exited, but where I had been in a former exit save. Sometimes my character will be the only thing that didn't properly copy over, and I'll have double resources (because I put others in a chest after getting back to my base after whatever I was doing). This most recent error at the time of my posting this, I loaded in facing the TCon smeltery despite (I think) exiting and saving in my base. This is an inconsistent problem, and not one I experience in other modpacks (no shade). I do not know how this could be happening

### Your Proposal

Would you mind taking a look at the game saving mechanisms? Mainly for character inventory and location, and of course whatever else is added as a character save file.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
> Would you mind taking a look at the game saving mechanisms? Mainly for character inventory and location, and of course whatever else is added as a character save file.

That's strictly vanilla. There is absolutely no mod that can possibly be touching that.

[It could be corruption](https://www.reddit.com/r/feedthebeast/comments/1zj71j/world_not_saving/), but I can't tell from your words alone.

You'd probably find more indications of the issue in your logs
