### ISSUE TITLE
Ores look like regular stone

### ISSUE THREAD

**Issue by Layedb4ck** [DrParadox7/Lost-Era-Modpack#112]
### Your Pack Version

1.6.7

### Type of Instance

Single Player

### Your Expectation

I cant find some ores anywhere. 

### The Reality

So some ores are invisible or only partially visible. They look like regular Stone when they are adjacent to it. Bauxit is also affected and i maybe some other too which i didn't find. is it some kind of option that can be disabled or a bug? (https://www.merriam-webster.com/dictionary/partially)  ![2024-09-30_00 42 27](https://github.com/user-attachments/assets/50d95ca9-8605-45a1-b8fc-c664382cbab1) 

### Your Proposal

I hope there is a quick answer to this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FlamingKetchup** [comment]
Gregtech ores are just like this iirc. I believe the intent is to have ores hidden as stone without being buried behind stone.

**Comment by DrParadox7** [comment]
This is the intended behaviour from GT4. Follow the quest and its explanation of hammer tapping (Steam Era) and scanners (Electric Era).

**Comment by Layedb4ck** [comment]
Thanks for the explanation.
