### ISSUE TITLE
WarpDrive-Mining Laser

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#12]
### Your Pack Version

1.4.3

### Type of Instance

Multiplayer

### Your Expectation

Can't craft the item from the workbench, even through NEI says I have all the items and they have the right IDs.
![2022-01-21_23 56 27](https://user-images.githubusercontent.com/46408153/150610963-c14ddf37-46d7-4c72-a41d-a67e40cd9ef4.png)

![2022-01-21_23 57 16](https://user-images.githubusercontent.com/46408153/150610970-88c172fd-27f5-4acf-8173-9082b30c2666.png)

### The Reality

It does not show an output.

### Your Proposal

Make it able to craft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Needs to be a miner robot and NEI clearly isn't picking it up. 
I managed to fix it using ore dictionaries:
![image](https://user-images.githubusercontent.com/47131096/150639336-a5758931-0c9b-4fd7-a648-5f530f8e84dd.png)

**Comment by SwedishKaito** [comment]
![2022-01-22_13 57 53](https://user-images.githubusercontent.com/46408153/150639493-5a14adf3-ac37-4d5f-b386-ec2b7c7add8e.png)
![2022-01-22_13 57 54](https://user-images.githubusercontent.com/46408153/150639498-48d8555d-3bcb-4933-a6e2-be87ad8e6cb4.png)

I crafted the Laser Tree Farmer without looking and guess what? They are the same recipe.

**Comment by SwedishKaito** [comment]
![2022-01-22_14 19 34](https://user-images.githubusercontent.com/46408153/150640118-9d1da0dd-5714-46e2-be9d-4b49430a0d9b.png)
