### ISSUE TITLE
WarpDrive - Ship Core - Keep EU/RF when broken.

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#14]
**Is your feature request related to a problem? Please describe.**
Whenever I break the ship core, I lose the power stored in it. Since it can keep 100 million EU, it seems dumb that the power isnt saved when it is broken.

**Describe the solution you'd like**
I would like it to keep the power stored in the ship core when it is broken.

**Describe alternatives you've considered**
N/A

**Comment by DrParadox7** [comment]
With WarpDrive being closed source this seems unlikely to be fixed.
