### ISSUE TITLE
WarpDrive - Air Canister wont fill when rightclicked on air generator.

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#16]
### Your Pack Version

1.4.3

### Type of Instance

Multiplayer

### Your Expectation

I rightclicked on an advanced air generator holding an empty air canister hoping it would fill it with air.

### The Reality

Instead, it poofed into thin air.

### Your Proposal

Please make sure that the air canister is returned to the player with a filled canister.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
I can't reproduce this.

**Comment by DrParadox7** [comment]
If it is caused by what I think it is it should be solved in the upcoming update
