### ISSUE TITLE
NEI / WAILA name mistakes

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#18]
### Your Pack Version

1.4.3

### Type of Instance

Multiplayer

### Your Expectation

-

### The Reality

![2022-01-25_16 04 34](https://user-images.githubusercontent.com/46408153/151002670-6a1279ec-dc5a-4fce-9145-e6f1b5931a2b.png)
![2022-01-25_15 51 29](https://user-images.githubusercontent.com/46408153/151002686-6a9b7ac0-d564-44a3-940d-ba4543d61452.png)

![2022-01-25_15 55 08](https://user-images.githubusercontent.com/46408153/151002709-76399d16-0d68-4917-a3ab-33a6af83d52c.png)

![2022-01-25_15 55 31](https://user-images.githubusercontent.com/46408153/151002713-4d8dbc02-448c-4b55-a562-a8a782e90814.png)
![2022-01-25_15 57 54](https://user-images.githubusercontent.com/46408153/151002724-0d1891d2-0818-460a-a882-ebe85ca136ab.png)
![2022-01-25_15 57 59](https://user-images.githubusercontent.com/46408153/151002733-73db7464-f155-47eb-87d8-2c0a8ab71b28.png)
![2022-01-25_16 00 34](https://user-images.githubusercontent.com/46408153/151002746-5b7172aa-b940-43bb-991f-b40ceef0dddc.png)
![2022-01-25_16 01 51](https://user-images.githubusercontent.com/46408153/151002753-9787d5ab-5a98-4e29-8b1f-f358c5bccae4.png)
![2022-01-25_16 01 53](https://user-images.githubusercontent.com/46408153/151002765-ba087ba2-52b5-4f37-b92a-49e691bd595a.png)
![2022-01-25_16 02 00](https://user-images.githubusercontent.com/46408153/151002781-36d0cf1a-045b-4219-a54e-8417cd434ff3.png)
![2022-01-25_16 04 33](https://user-images.githubusercontent.com/46408153/151002792-8a1bc1e2-3d16-4602-bd1d-d656f2e193d2.png)

![2022-01-25_15 52 01](https://user-images.githubusercontent.com/46408153/151002701-2db16d89-410d-4cdc-b7b0-19a27acaaa16.png)

![2022-01-25_15 51 59](https://user-images.githubusercontent.com/46408153/151002693-179e1ddc-a2a9-47b2-a9cc-1d73c5977b90.png)

![2022-01-25_16 09 29](https://user-images.githubusercontent.com/46408153/151003489-5e8a860f-7dfe-464b-9cb1-eff46cb3683a.png)
![2022-01-25_16 09 32](https://user-images.githubusercontent.com/46408153/151003507-405f873c-a023-4322-853e-b86526a2ace8.png)
![2022-01-25_16 09 36](https://user-images.githubusercontent.com/46408153/151003513-08bf30ce-e51a-47f0-9371-6cdce944d882.png)
![2022-01-25_16 09 39](https://user-images.githubusercontent.com/46408153/151003529-b4b2b4b9-c90f-4772-bacb-fa2c2903a26e.png)
![2022-01-25_16 09 41](https://user-images.githubusercontent.com/46408153/151003536-30d7e81c-615c-45ad-8096-a719afafad37.png)
![2022-01-25_16 09 42](https://user-images.githubusercontent.com/46408153/151003543-59673801-532a-4980-9c48-d2fe794498e7.png)
![2022-01-25_16 09 45](https://user-images.githubusercontent.com/46408153/151003553-2e56c0bd-3046-46df-b4dd-361eb732eda5.png)
![2022-01-25_16 09 47](https://user-images.githubusercontent.com/46408153/151003565-173c1184-a2e4-465a-82a8-120ac6aa4e0f.png)

(the etfuturum stuff has a bunch of errors between ID 2071-2080 which is "wall_sign_ [..] and sign_ [..].)

then theres also a WAILA name issue
![2022-01-25_16 13 54](https://user-images.githubusercontent.com/46408153/151003955-bc18a261-74e9-4455-bae3-aec0ae51c972.png)

![2022-01-25_16 24 02](https://user-images.githubusercontent.com/46408153/151005760-7327b9df-ac0c-4edb-836a-c18aa34cb7bf.png)

### Your Proposal

Hide them from NEI if theyre not needed. Fix those that are needed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SwedishKaito** [comment]
![2022-01-25_22 01 40](https://user-images.githubusercontent.com/46408153/151059154-a3f0e136-2d87-4872-ac3d-e99d630cc5b5.png)

**Comment by DrParadox7** [comment]
These issues are easy to fix but are fairly time consuming.

Locally it is extremely easy to fix them. If it bothers you I've added a script for contributors to fix langs with instructions here:
https://github.com/DrParadox7/Lost-Era-Modpack/blob/main/scripts/LangFixes.zs

Hiding stuff from NEI can be done in NEI.zs and only requires IDs:
https://github.com/DrParadox7/Lost-Era-Modpack/blob/27d7236946dd8bea05fe999ee5225a9b7c90ff18/scripts/NEI.zs#L112

IDs can be fetched by holding the item in question and using the command `/mt hand`.
