### ISSUE TITLE
Serve Pack download?

### ISSUE THREAD

**Issue by KongGal** [DrParadox7/Lost-Era-Modpack#2]
Is there a server pack anywhere for download?  
"The M.E.T.A. is playing with friends for trading goods and services."  
  
but i don't see a server download to be able to play with friends

**Comment by DrParadox7** [comment]
I want to first make sure I don't miss any important config and that the installation process is painless.
You'll see one within 48h.

**Comment by KongGal** [comment]
https://github.com/Yoosk/ServerStarter  Have a look at this, very easy and simple way to create server packs, i saw Ragnamod use it  try and check their server pack, maybe its something you could use as well.  https://www.curseforge.com/minecraft/modpacks/ragnamod-vi/files  
  on the ServerStarter repo you find the 3 important files server-setup-config.yaml and then src/main/resources is where the bat and sh is, all 3 files just need to be tweaked and then its very easy to start a server after that, maybe try theirs server installer and have a look at how it works

**Comment by DrParadox7** [comment]
It's not a difficulty of creating one but rather make sure everything is stable on the client-side before releasing something server-side.

**Comment by DrParadox7** [comment]
It is now available on Curseforge. Do let me know if anything is broken/missing.
