### ISSUE TITLE
HIGH PRIO - Outdated Thaumic Expansion mod is removed from ModLoader server, unable to install pack.

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#25]
### Type of Instance

Single Player

### Installation Target

Your Own Computer or Laptop

### Your Actions

![image](https://user-images.githubusercontent.com/46408153/152648876-acef6a9e-a78f-4827-9749-3881c904450e.png)

the 1.8.2-GTNH version of Thaumic Expansion has been updated to 1.8.3 less than a day ago, and removed 1.8.2 from the server which hosts the mod. 

![image](https://user-images.githubusercontent.com/46408153/152648947-e1368b0f-e653-41e5-8fa6-701bff79e619.png)

### Your Pack Version

1.4.4a

### Required Logs

-

### Final Checklist

- [X] I have provided all the required logs.
- [X] I searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by SwedishKaito** [comment]
for now, I will include the 1.8.2 .jar file here for the mod until the pack has been updated.
[Thaumic-Exploration-[1.7.10] 1.1.82-GTNH-0.zip](https://github.com/DrParadox7/Lost-Era-Modpack/files/8008323/Thaumic-Exploration-.1.7.10.1.1.82-GTNH-0.zip)

**Comment by DrParadox7** [comment]
I’ll get it sorted as soon as I can a computer setup. 
Thanks for providing a workaround for those who can’t wait

**Comment by DrParadox7** [comment]
Fixed with release v1.4.5.
