### ISSUE TITLE
Unkillable entities

### ISSUE THREAD

**Issue by LiprikON2** [DrParadox7/Lost-Era-Modpack#28]
### Your Pack Version

1.4.5a

### Type of Instance

Single Player

### Your Expectation

Attack/break all entities, see them show up in WAILA

### The Reality

Some of the zombies cannot be attacked and also one minecart with chest I found cannot be broken. They aren't showing up in WAILA either. So far only lava helped in killing them.

In the attached save file you are in front of unkillable zombie with a bow, and above him, on a wooden platform, you can find minecart with a chest in question. (-58 24 -216 coords)
[Entity-bug save.zip](https://github.com/DrParadox7/Lost-Era-Modpack/files/8119016/Entity-bug.save.zip)

### Your Proposal

Make entities killable again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LiprikON2** [comment]
`The Lost Era Modpack\minecraft\logs` folder
[logs.zip](https://github.com/DrParadox7/Lost-Era-Modpack/files/8119073/logs.zip)

**Comment by DrParadox7** [comment]
Bug is present in the base vanilla game and not caused by any part of the modpack. 

More info can be found at Mojang’s bug tracking site, specifically [MC-2713](https://bugs.mojang.com/browse/MC-2713)
