### ISSUE TITLE
Command blocks

### ISSUE THREAD

**Issue by KongGal** [DrParadox7/Lost-Era-Modpack#3]
Started a server op and very quickly i found a "structure" with colored glass as floor and in the middle was a command block, i would advise strongly against having command blocks in the world on a server level since any player could break the glass and run any command they would want with no restrictions

**Comment by DrParadox7** [comment]
> Run any command they would want with no restrictions
Command blocks cannot be mined in Survival and can only be edited by players with operator status (i.e. /OP "playername")
