### ISSUE TITLE
Basic Gas tank - no recipe

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#32]
### Your Pack Version

1.4.5a

### Type of Instance

Multiplayer

### Your Expectation

I wanted to craft a mekanism gas tank

### The Reality

there was no recipe for it

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Fixed in 1.4.6. This only occurs on our server side for unimplemented commits.

https://github.com/DrParadox7/Mekanism/commit/7ee93acdb834f7385798b80b6a4d3f9d13eb814b
