### ISSUE TITLE
Cooking Table - Armor Removal Bug

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#33]
### Your Pack Version

1.5.0b

### Type of Instance

Single Player

### Your Expectation

I want to make food without my armor disappearing in the cooking table.

### The Reality

The armor disappears until you click an armor slot when in inventory.

https://user-images.githubusercontent.com/46408153/182640417-7be354b4-5067-4cdd-a6af-85374a565765.mp4

### Your Proposal

I want my armor to keep being on when I use the cooking table.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
It's a current bug with Cooking with Blockheads.

Until they fix it on their side, armor will disappear only until refreshed by either:
-Taking any kind of damage
-Interacting with the armor slot
-Switching dimensions

**Comment by DrParadox7** [comment]
Fixed on v1.5.3
