### ISSUE TITLE
Soul Tethered Bugs

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#34]
### Your Pack Version

1.5.1

### Type of Instance

Single Player

### Your Expectation

Soul Tether should save my items like Soulbound.
There is also two Soul Tether enchantments.

### The Reality

It doesn't.

and this..
![image](https://user-images.githubusercontent.com/46408153/182717492-f45d3d1b-2c72-4873-a247-f35570ac7c20.png)

### Your Proposal

Just want it to work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Fixed in 1.5.2 with AM2 [v1.4.0.014](https://github.com/DrParadox7/ArsMagica2/releases/tag/v1.4.0.014)

**Comment by SwedishKaito** [comment]
Nope, it still present in 1.5.2 MP.

**Comment by DrParadox7** [comment]
Steps to reproduce?
From my tests it does save your items on death

**Comment by SwedishKaito** [comment]
As tested on MP; this issue is now closed.
