### ISSUE TITLE
Ars Magica 2 LE - Disconnect from Multiplayer when Buff runs out.

### ISSUE THREAD

**Issue by Eb-** [DrParadox7/Lost-Era-Modpack#35]
### Summary

When playing in multiplayer, if a buff / debuff runs out, the player immediately gets kicked with the following error:

![image](https://user-images.githubusercontent.com/2814500/185464473-75d49257-bff0-4d60-b0c2-7242778c839d.png)

Oddly, this does not get written to `latest.log`, i have transcribed it manually below for ease of indexing.

>Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet was larger than I expected, found 3 bytes extra whilst reading packet 30

Removing Ars Magica 2 from the pack resolves this issue.

It looks like this was patched in pull request from the origin branch's source, but has not been merged: https://github.com/jss2a98aj/ArsMagica2/pull/1

Suggested solution would be to pull this patch to fix this issue to the https://github.com/DrParadox7/ArsMagica2 package. (Enabling the issue tracker for that branch will also help issues like this be more easily reported!)

----
### Logs

Taken a snippet of the event, playername and ip address has been obscured to "player" as per their request. Oddly, the client log does not write the above error to the log, however it does display it on the screen.

Serverside log snippet of the event (connecting, spawning a potion of regeneration, using it, losing connection):

> [11:22:40] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
> [11:22:40] [Server thread/INFO]: player[/<obscured IP>] logged in with entity id 572 at (213.69999998807907, 64.0, 269.69999998807907)
> [11:22:40] [Server thread/INFO]: player joined the game
> [11:23:04] [Server thread/INFO]: [player: Given [Splash Potion of Regeneration] * 1 to player]
> [11:23:40] [Server thread/INFO]: player lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
> [11:23:40] [Server thread/INFO]: player left the game

Clientside log snippet of the event:

> [11:22:38] [Client thread/INFO]: Connecting to obscured.server.address, 25565
> [11:22:42] [Client thread/INFO]: [CHAT] Welcome to the server!
> [11:22:43] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
> [11:23:04] [Client thread/INFO]: [CHAT] Given [Splash Potion of Regeneration] * 1 to player
> [11:28:25] [Client thread/INFO]: Stopping!

**Comment by DrParadox7** [comment]
I can't help you with logs

**Comment by Eb-** [comment]
Posted on behalf of another, let me grab the log and attach to the original post.

**Comment by Eb-** [comment]
Updated main thread with logs of the incident, please let me know if you need any further information. It looks like there is already a fix [here](https://github.com/jss2a98aj/ArsMagica2/pull/1/commits/c421536964358537a4bbe0954e0b538e6e344d90), though I don't currently have the ability to compile to test if this fixes the issue.

**Comment by DrParadox7** [comment]
I will need the full logs

**Comment by Eb-** [comment]
Sorry for the delay, didn't get time to dig into this until the weekend. Log is attached, error is on lines 35904 and 35944. Did a little further troubleshooting to recreate the issue as well.

[LostEra-fml-client-latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/9389701/LostEra-fml-client-latest.log)

Turns out, [ExtendedPotions](https://www.curseforge.com/minecraft/mc-mods/extended-potions) was disabled in their server and client. By enabling ExtendedPotions, it adds a handler to allow further potion effects, which ArsMagica2LE appears to benefit from. Without ExtendedPotions installed, any buffs the player receives will be met with this disconnect bug.

So, in the case of the Lost Era Modpack, a non-issue, but in the case of AM2LE specifically, is an issue.

If a direct fix is not able to be applied, perhaps marking ExtendedPotions as a dependency of AM2LE would be a  workaround?

**Comment by DrParadox7** [comment]
No. It's enough for me to support a bugs and crashes in the Lost Era modpack.
If a user wants to change something in the pack they must bear the responsibility for it.

I don't provide support for any modification done to it.

**Comment by Eb-** [comment]
Regardless, thank you for your time and attention! Have a great one :beers:
