### ISSUE TITLE
Ticking Entity Crash when hit by plague zombie

### ISSUE THREAD

**Issue by JonnaJudin** [DrParadox7/Lost-Era-Modpack#4]
Started the game, collected some wood and walked around spawn, attacked and killed a fire zombie, afterwards attacked and hit a plague zombie and game crashed. Will disabling the Special Mobs mod affect the quests completion or anything else super relevant?

Stack info:
Description: Ticking entity
java.lang.NoClassDefFoundError: in
	at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:891)
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:642)
	at toast.specialMobs.EffectHelper.stackEffect(EffectHelper.java:51)
	at toast.specialMobs.EffectHelper.plagueEffect(EffectHelper.java:90)

-- Entity being ticked --
Details:
	Entity Type: SpecialMobs.PlagueZombie (toast.specialMobs.entity.zombie.EntityPlagueZombie)
	Entity ID: 21796
	Entity Name: Plague Zombie
	Entity's Exact location: -115.42, 70.00, 27.43
	Entity's Block location: World: (-116,70,27), Chunk: (at 12,4,11 in -8,1; contains blocks -128,0,16 to -113,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.07, -0.08, -0.08

**Comment by DrParadox7** [comment]
That's actually nothing to do with Special Mobs but rather a change in installation forced on me by CurseForge causing this crash on the very first time you launch the game.

I am currently working on it as we speak and will release an update very soon.

**Comment by DrParadox7** [comment]
Fixed in 1.3.8
