### ISSUE TITLE
Ars Magica 2 Crafting Altar crashes the game

### ISSUE THREAD

**Issue by ImkoesterI** [DrParadox7/Lost-Era-Modpack#42]
### Your Pack Version

1.5.2

### Type of Instance

Single Player

### Your Actions

I created a new single player creative world and took a Crafting Altar (ArsMagica2) out of the inventory. I then placed it and the game crashed 

### Crash Report

[fml-client-latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/9961446/fml-client-latest.log)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by ImkoesterI** [comment]
So I tried it one more time this time my Minecraft closed itself completly here is the log for that (I dont know if there is something different about it) 

[Minecraft Log.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/9961737/Minecraft.Log.txt)

**Comment by ImkoesterI** [comment]
sry that it took so long for me to answer. I tried it just now and it seems to work now. Thx a bunch for your help :)

**Comment by DrParadox7** [comment]
Fixed in next version
