### ISSUE TITLE
enchantment.Soul Tether I

### ISSUE THREAD

**Issue by SwedishKaito** [DrParadox7/Lost-Era-Modpack#45]
### Your Pack Version

1.5.4

### Type of Instance

Single Player

### Your Expectation

I want "Soul Tether I" to be on my items. 

### The Reality

Instead I have enchantment.Soul Tether I.

### Your Proposal

Change it to Soul Tether I.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Fixed in 1.6.2
