### ISSUE TITLE
Crash with Call of the Zephyr ritual

### ISSUE THREAD

**Issue by ipl-adm** [DrParadox7/Lost-Era-Modpack#47]
### Your Pack Version

1.5.5

### Type of Instance

Multiplayer

### Your Actions

just placed this ritual to pickup potatoes and got crash

### Crash Report

[crash-2023-01-06_17.42.36-server.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/10360853/crash-2023-01-06_17.42.36-server.txt)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Possible Storage Drawers issue.
More testing required

**Comment by DrParadox7** [comment]
Fixed next update (v1.5.6)
