### ISSUE TITLE
minecraft instantly closes upon startup when I add other mods

### ISSUE THREAD

**Issue by mcmso** [DrParadox7/Lost-Era-Modpack#48]
### Your Pack Version

1.5.5

### Type of Instance

Single Player

### Your Expectation

Hello, I am very happy to update 'The Lost Era'modpack to 1.5.5
However, when my friends and I tried to expand Botania, we found that the recently updated botania-1.7.10-1.9-le. jar seemed to be not compatible with Alfheim-RC-41.jar. If you could help us solve this problem, we would really appreciate it. I hope you can contact me if you need any documents and I will give you feedback immediately

### The Reality

To reproduce, just add 1.7.10-ASJCore-1.2.1.0.jar and Alfheim-RC-41.jar to modpack
Paste:
 log:https://paste.ubuntu.com/p/CwCyR6FgXd/ 
 crash-reports:https://paste.ubuntu.com/p/9mK7y6vmfj/

[latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/10361487/latest.log)

[crash-2023-01-07_00.11.57-client.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/10361483/crash-2023-01-07_00.11.57-client.txt)

### Your Proposal

I know that asking you to solve a problem other than modpack will disturb you, but I hope to get your help, thank you

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
That's just not happening:

1.) Alfheim's performance is beyond dreadful and prone to crashes.
2.) I won't be putting work or support private remixes of my pack.

**Comment by mcmso** [comment]
> That's just not happening:
> 
> 1.) Alfheim's performance is beyond dreadful and prone to crashes. 2.) I won't be putting work or support private remixes of my pack.

It’s okay, I understand that you have a lot of things to do in a day, I’m already mentally prepared for this, thank you for your reply, thank you
