### ISSUE TITLE
Ichor does not unlock even though the command /isichorunlocked says yes

### ISSUE THREAD

**Issue by ImkoesterI** [DrParadox7/Lost-Era-Modpack#49]
### Your Pack Version

1.5.5

### Type of Instance

Multiplayer

### Your Expectation

I unlocked every research from the normal Thaumcraft and from Thaumic Tinkers and then used the command /iskamiunlocked, which shows what you still need to research to unlock kami, which should unlock Ichor. After I used the command i got back a "yes" , which should mean that I am able to research Ichor sadly I cannot

### The Reality

After using the command and getting back a yes I still could not research Ichor

### Your Proposal

Checking whether the /iskamiunlocked command works correctly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Yeah, that command won‘t work well on this pack (if not at all). 

The quest does a better job in telling you how to get there.
