### ISSUE TITLE
[Crash] Crash when colliding with purple slime block (NoClassDefFoundError)

### ISSUE THREAD

**Issue by ClockwiseGear** [DrParadox7/Lost-Era-Modpack#5]
Pack Version: 1.3.7a, fresh install

Launcher: Curseforge

RAM allocated: 7520 MB

Description:
After spawning in a brand new world, I was on a Tinker's slime island with a blue slime and some purple slime blocks. I attempted to break one of them with my hand and the game crashed.

Crash log:
[Link](https://gist.github.com/ClockwiseGear/bb4abff65f3a76d0b0dc3a0fce720057)

**Comment by ClockwiseGear** [comment]
Upon loading the world again, I have the block I was mining in my inventory and am able to place, jump on, and break it without issue.

**Comment by DrParadox7** [comment]
Same as #4. One of the third party mods needs to be loaded before the game launches.
I've sent a request for CurseForge to allow this so we will have to wait for their response.

To summarize for others reading this:
On your very first launch additional mods that are not on Curseforge get downloaded and one of them does not get loaded properly causing it to only be partially loaded and crash as a result when missing classes are called.

It can only ever happen that very first launch and subsequent launches will work fine as the file exists in your folder on startup.

**Comment by DrParadox7** [comment]
Fixed in 1.3.8
