### ISSUE TITLE
NuclearCraft steam incompatibility

### ISSUE THREAD

**Issue by Haxmann** [DrParadox7/Lost-Era-Modpack#50]
### Your Pack Version

1.5.5

### Type of Instance

Multiplayer

### Your Expectation

I was trying to set up thermal boiler from GT4 to produce steam used by kinetic steam generators from IC2, because they're cheaper than Railcraft's steam turbine.

### The Reality

However, it appears that the thermal boiler outputs NuclearCraft steam (liquid:steam), instead of it's IC2 counterpart (liquid:ic2steam), which kinetic steam generators won't accept. Further examination on clean instance with only IC2 and GT4 showed that the boiler is, in fact, produces ic2steam when NuclearCraft is not present, and when added to instance, the contrary happens. 

### Your Proposal

It seems that the issue is [previously known](https://github.com/tomdodd4598/NuclearCraft/issues/216) with relations to Thermal Expansion, but nothing was done about it. There was still hope in MineFactory's unifier, but it does not convert any liquid besides ethanol and biofuel, [by the looks of it](https://github.com/skyboy/MineFactoryReloaded/blob/15bfedb8f1efee7fcd6f904558883e6137d2e71b/src/main/java/powercrystals/minefactoryreloaded/tile/machine/processing/TileEntityUnifier.java#L210). Renaming .jar files to change the loading order of the mods doesn't to make any difference, and after searching the CraftTweaker documentation, I believe that there is no actual way to modify the fluid registry with it. I don't really know how hard it would be to change NuclearCraft's liquid registration or modify the liquid conversion logic of the MineFactory's unifier, but any of those fixes will do the trick, I think.

However, if it is not possible, easier recipe for the Railcraft's steam turbine would be gladly appreciated.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
This should be easily fixable since we have forked both mods.

I'll have a look over the weekend.

**Comment by DrParadox7** [comment]
@Haxmann Try seeing if this fixes it:
https://github.com/DrParadox7/GregTech4/releases/download/v4.15.43LE/gregtechmod-v416.43LE.jar

**Comment by Haxmann** [comment]
> @Haxmann Try seeing if this fixes it: https://github.com/DrParadox7/GregTech4/releases/download/v4.15.43LE/gregtechmod-v416.43LE.jar

This is indeed fixes the problem, thank you very much!

**Comment by DrParadox7** [comment]
Fixed next update (v1.5.6)
