### ISSUE TITLE
Unobtainable refined iron casings

### ISSUE THREAD

**Issue by Haxmann** [DrParadox7/Lost-Era-Modpack#51]
### Your Pack Version

1.5.5

### Type of Instance

Multiplayer

### Your Expectation

Attempting to craft refined iron casings by GT4 means (alloy smelter, plate cutting machine, extruder).

### The Reality

This item is only obtainable in metal former, which is disabled for crafting.

### Your Proposal

Adding respective recipes for alloy smelter, plate cutting machine, extruder.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Fixed in v1.5.5.
Available at https://github.com/DrParadox7/GregTech4/releases/download/v4.15.43aLE/gregtechmod-v416.43aLE.jar
