### ISSUE TITLE
Witchery Magic Mirror not becoming Hollow

### ISSUE THREAD

**Issue by Kaine-Arcane** [DrParadox7/Lost-Era-Modpack#59]
### Your Pack Version

1.5.7

### Type of Instance

Multiplayer

### Your Expectation

Go into the Magic Mirror's dimension
The Reflection loads the player's skin
The Reflection can be damaged and killed
Once killed, the Mirror becomes a Hollow Magic Mirror instead of an Inhabited one
The player may leave by jumping into the Mirror behind where they loaded into the Mirror's dimension

### The Reality

Go into the Magic Mirror dimension
The Reflection has a completely white skin with barely noticable features
The Reflection has a hitbox, but cannot be interacted with in any way other than it being able to attack you, and does not show up on WAILA
After relogging while inside the dimension, the Reflection becomes attackable and they show up as normal on WAILA, but still do not copy the player skin
Killing the reflection drops their loot as normal
The player cannot leave through the mirror and must leave through teleporting out via a Return Scroll or other form of Cross Dimensional Teleporting
The Mirror doesn't update to being Hollow and stays Inhabited even if the Reflection is slain, and the reflection respawns upon re-entering

### Your Proposal

Find out why the Mirror is broken

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Kaine-Arcane** [comment]
Spawning in a new mirror fixed my issue with not being able to leave the dimension, however, the Reflection is still not loading a skin and is not vulnerable until relogging inaide the dimension, and it typically kills a player before they can act outside of Creative Mode

**Comment by DrParadox7** [comment]
I double-checked and you can both hit the reflection and leave the mirror just fine except it is hard to leave when you are being hit while the slowness effect is applied to both you and the reflection.
![Mirror](https://user-images.githubusercontent.com/47131096/231015265-a85d46cb-e9ca-404f-97c5-6b8036cc524a.gif)
_I ate an Enchanted Golden Apple here but any effect on me gets also applied to the reflection._

As for the reflection not rendering the player's skin, it must be something done by Mojang as that no longer works with Witchery alone. We'll try looking into it.
