### ISSUE TITLE
25% of quests are missing descriptions

### ISSUE THREAD

**Issue by Pjbomb2** [DrParadox7/Lost-Era-Modpack#61]
### Your Pack Version

1.5.7

### Type of Instance

Multiplayer

### Your Expectation

Quests in the quest book would be properly descripted

### The Reality

Several crucial things are missing their descriptions instead replaced with things like 
lostera.quest664.desc
Which was an important one as it told me I could pipe in mekanism gasses into the nuclearcraft fusion reactor, but since it didnt show, I didnt know that for awhile(until someone looked at the actual file)

### Your Proposal

The quests need to be fixed, even if its slowly over time, as they can contain crucial information that is important to the operation of the target/subject of the quest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SwedishKaito** [comment]
This is fixed in next update as this is fixed in commit;
https://github.com/DrParadox7/Lost-Era-Localizations/commit/f838e9c2eb253061b8dfe79f13e2e47019c31fd0

**Comment by DrParadox7** [comment]
Fixed in v1.5.8. 
If you still find any issues about quest localizations do let me know here and I'll reopen this.
