### ISSUE TITLE
Syncotron controller cant be made

### ISSUE THREAD

**Issue by Pjbomb2** [DrParadox7/Lost-Era-Modpack#63]
### Your Pack Version

1.5.8

### Type of Instance

Multiplayer

### Your Expectation

Entered the syncotron controller recipie as shown in jei, but it doesnt work

### The Reality

recipie is invalid

### Your Proposal

The syncotron controller recipie needs to be fixed, one thing I noticed was that it used a superconducting electromagnet that doesnt have a recipie, giving me the idea that it could be using a different block than the one we can craft

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
This is already fixed in v1.5.8
