### ISSUE TITLE
Tinker's Construct Crafting Table crashes when opened next to a Smoker

### ISSUE THREAD

**Issue by CRF0806** [DrParadox7/Lost-Era-Modpack#64]
### Your Pack Version

1.5.8

### Type of Instance

Single Player

### Your Actions

Place a smoker next to a TC crafting table.
Attempt to open the crafting table.
Crash shortly afterwards.

### Crash Report

[crash-2023-05-25_19.56.54-server.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/11570171/crash-2023-05-25_19.56.54-server.txt)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
It should be fixed in v1.6.0
