### ISSUE TITLE
Two cotton recipes with different results

### ISSUE THREAD

**Issue by hatalmasalma** [DrParadox7/Lost-Era-Modpack#66]
### Your Pack Version

1.5.8

### Type of Instance

Single Player

### Your Expectation

![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/65861307/5f88daca-1876-4e2d-8963-cf5c4d2f4bc4)
![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/65861307/5b17915f-64c6-4e7d-9879-d7869115d68f)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
It's mainly a graphical issue rather than a gameplay issue.
Even if you try to follow the shaped string recipe you will still get 2 strings rather than 1 so its pretty harmless and a script for it is overkill.
