### ISSUE TITLE
Certain molten metals cannot be poured in steel cast, only clay cast. 

### ISSUE THREAD

**Issue by Ic3wolf21** [DrParadox7/Lost-Era-Modpack#67]
### Your Pack Version

1.5.8

### Type of Instance

Multiplayer

### Your Expectation

When pouring certain molten metal (Damascus) into a steel cast the metal does not pour. 
I expect the metal to pour into steel cast.

### The Reality

What happens for example with Damascus steel. While using a clay cast it pours and does not consume the clay cast allowing reuse of the clay cast, but while using a steel cast it does not pour. This is for ingots or tool pieces.

### Your Proposal

Allow certain molten metals (ex. Damascus Steel) to be cast in steel cast not only clay cast.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
It should be fixed in v1.6.0
