### ISSUE TITLE
Server download

### ISSUE THREAD

**Issue by VincentStrand** [DrParadox7/Lost-Era-Modpack#68]
A dedicated server download would be nice for people not hosting with a 3rd party service. 
 If there is already one I cannot find a link on Modrinth, Curseforge, or github.

**Comment by DrParadox7** [comment]
We have it already on both Curseforge (separate file) and Modrinth (all-in-one).
![Server-Support](https://github.com/DrParadox7/Lost-Era-Modpack/assets/47131096/5ce52754-e805-4d08-828e-7b4da7f9fd10)
