### ISSUE TITLE
Server Pack Not Downloading All Mods

### ISSUE THREAD

**Issue by AzureDoom** [DrParadox7/Lost-Era-Modpack#7]
Trying to configure a server with this modpack and it is missing things such as OpenComputers and Tinkers.

**Comment by DrParadox7** [comment]
I’m going to need more info, preferably in the form of logs

**Comment by DrParadox7** [comment]
I'll close this issue for lack of info. If you're able to provide me with the appropriate logs I will re-open and have a look at it again.

There are far too many external factors such as antiviruses, firewall settings or even limitations provided by cloud services that can get in the way of downloads for me to identify and fix the issue.
