### ISSUE TITLE
Villager selling knowledge fragment

### ISSUE THREAD

**Issue by hatalmasalma** [DrParadox7/Lost-Era-Modpack#71]
### Your Pack Version

1.5.8

### Type of Instance

Single Player

### Your Expectation

.

### The Reality

.
![2023-07-22_02 07 24](https://github.com/DrParadox7/Lost-Era-Modpack/assets/65861307/a0e12b2c-3a93-42b2-8ca5-e550efda70d3)

### Your Proposal

I'm not too familiar with those ender-thingies, but I suspect it shouldn't be available to buy in mass.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
That's intentional by Thaumcraft afaik

**Comment by DrParadox7** [comment]
> Thaumaturge villagers will accept emeralds in exchange for the following:
...
**-Knowledge Fragments**

https://thaumcraft-4.fandom.com/wiki/Thaumic_Villagers
