### ISSUE TITLE
BetterQuest mod config not available (both from main menu and in-game)

### ISSUE THREAD

**Issue by hatalmasalma** [DrParadox7/Lost-Era-Modpack#72]
### Your Pack Version

1.6.0

### Type of Instance

Single Player

### Your Expectation

In 1.5.8 it worked, both from main menu and in-game:

![bq 1 5 8](https://github.com/DrParadox7/Lost-Era-Modpack/assets/65861307/c9bed491-5577-4b96-b598-41a5d9f8e42b)

### The Reality

In 1.6.0 the option doesn't appear. During update I copied a few files over, but after testing with a new, clear install, the result is the same:

![bq 1 6 0](https://github.com/DrParadox7/Lost-Era-Modpack/assets/65861307/8ba83e21-e465-4c12-a797-05412a06401f)

### Your Proposal

I'm using MultiMC, downloading from Modrinth.
I viewed the mcmod.info in the jars, and they have several differences.
I suspect the newer one is malformed, causing the "Config" and "Disable" buttons to disappear, because they reappear if other mods are selected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Mod has been greatly update.
You can still change the options via the config folder (not that you would need to do so).

I don't plan to undertake this task as it offers no benefit to the modpack
