### ISSUE TITLE
Can't install the modrinth version (MultiMC)

### ISSUE THREAD

**Issue by WeaselOnaStick** [DrParadox7/Lost-Era-Modpack#73]
### Type of Instance

Single Player

### Installation Target

Your Own Computer or Laptop

### Your Actions

Installing the modpack through MultiMC modrinth option (or importing `LostEra_Modpack_1.6.0.mrpack`) only downloads 2 mods (mcinstanceloader-2.6 and PokePatch-1.2b) but nothing else

### Your Pack Version

1.6.0

### Required Logs

https://paste.ee/p/MhFzf

### Final Checklist

- [X] I have provided all the required logs.
- [X] I searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
You are not meeting the modpack requirements:

![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/47131096/81ddf046-01fb-4a3e-bc60-6a1511ee7567)

**Required Java:** 8
**Your Java:** 18
