### ISSUE TITLE
Pack Crashes on Menu button clicks or world opened

### ISSUE THREAD

**Issue by LeonBoettcher** [DrParadox7/Lost-Era-Modpack#75]
### Your Pack Version

All

### Type of Instance

Single Player

### Your Actions

I startet the game, this appears, when i try to go in a world or create one, another error appears. Pack is unplayable

### Crash Report

[latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/12367225/latest.log)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
See if using this mod fixes it:
https://github.com/DrParadox7/Waystones/releases/tag/v1.0.1a-LE

**Comment by DrParadox7** [comment]
Closing as stale
