### ISSUE TITLE
AE2 Crafting multiblock always reverts to lowest tier on place

### ISSUE THREAD

**Issue by idk-some-guy** [DrParadox7/Lost-Era-Modpack#77]
### Your Pack Version

1.6.1

### Type of Instance

Single Player

### Your Expectation

placing a crafting storage or co processor should result in a multiblock with the same blocks.

### The Reality

Upon crafting a 16k crafting storage block and a couple co processors, whenever i place them they automatically change to 1k crafting storage and crafting unit block respectively. this happens both in my test creative world and a server.

### Your Proposal

Fixing the issue, or better yet, hotfixing as it completely breaks progression.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Fixed in 1.6.2
