### ISSUE TITLE
Wrong line endings make script unlaunchable on unix platforms

### ISSUE THREAD

**Issue by idk-some-guy** [DrParadox7/Lost-Era-Modpack#79]
### Type of Instance

Multiplayer

### Installation Target

Your Own Computer or Laptop

### Your Actions

Attempting to launch the startserver sh script fails with the following:

/bin/bash^M: no such file or directory.

replacing the line endings with the command: `sed -i -e 's/\r$//' startserver.sh` fixes it and script becomes launchable.

Tested on macOS, but should be same on linux.

### Your Pack Version

1.6.2

### Required Logs

no logs are produced or required as the script doesnt execute at all

### Final Checklist

- [X] I have provided all the required logs.
- [X] I searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by idk-some-guy** [comment]
Forgot to mention, testing the modrinth release

**Comment by DrParadox7** [comment]
Thanks for letting me know. I'll make sure to make a mini release soon to tackle it

**Comment by DrParadox7** [comment]
Fixed in the latest version of Modrinth.
Feel free to reopen if that's not the case
