### ISSUE TITLE
"A fatal error has occured, this connection is terminated" when trying to connect to server

### ISSUE THREAD

**Issue by loxfer72** [DrParadox7/Lost-Era-Modpack#80]
### Your Pack Version

1.6.2

### Type of Instance

Multiplayer

### Your Expectation

Tried to connect to my friend's server by direct connect and added server.

### The Reality

Got a "A fatal error has occured, this connection is terminated"
![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/56304676/00ecec4f-76d6-4c32-b8a1-36b0b6f62e54)
Before the update 1.6.2 it was fine

### Your Proposal

I already tried to redownload the modpack, also i can play in solo without getting this error so maybe its related to my profile on the server like an item linked to an updated mod

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Screenshots won't ever say enough to solve issues. I'll need more information in the form of a log

**Comment by loxfer72** [comment]
No, a friend just tried a few minutes ago and got the same error

**Comment by DrParadox7** [comment]
Have you guys tried loading a backup in case there is some type of corruption?

**Comment by loxfer72** [comment]
No the owner of the server is not avalable for now but surely will later, i will ask him to try and give you feedback.

**Comment by DrParadox7** [comment]
What I can tell you is that this is caused by a Compression Dynamo.
It is supposed to send a network packet with 3 values:
- Access Setting (Public, Private, Friends-Only)
- Owner's UUID
- Owner's Username
However, it is sending a non-valid UUID causing clients receiving it to crash.
This could very well be caused by corruption

**Comment by loxfer72** [comment]
So we did load a backup and now it works, thank you very much for your help and also for this great modpack.

**Comment by DrParadox7** [comment]
I'm glad to hear it..
