### ISSUE TITLE
Bloodmagic item loss

### ISSUE THREAD

**Issue by ItsPandemonium** [DrParadox7/Lost-Era-Modpack#81]
### Your Pack Version

1.6.1

### Type of Instance

Single Player

### Your Expectation

I was filling my Blood Altar using the sacrificial knife, and I accidentally killed myself. I expected to be able to respawn and pick up my items.

### The Reality

I was unable to click the respawn button, and could only exit to title screen. when I got back into my world, there was no grave at my death site, nor was there a death marker in my World Atlas.

### Your Proposal

maybe disable the ability to charge the sacrificial knife without incense? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
I cannot reproduce this bug.
Please provide a way to reliably reproduce this issue or provide the logs detailing the error.

**Comment by DrParadox7** [comment]
Closed for lack of information
