### ISSUE TITLE
Clicking "Baubles" in your inventory crashes the game

### ISSUE THREAD

**Issue by CRF0806** [DrParadox7/Lost-Era-Modpack#82]
### Your Pack Version

1.6.2

### Type of Instance

Multiplayer

### Your Actions

Click on the Baubles icon in the top-right side of the character portrait screen in your inventory.

Afterwards, the game will crash.

### Crash Report

[crash-2023-09-28_17.30.14-client.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/12754097/crash-2023-09-28_17.30.14-client.txt)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Issue fixed in unreleased commit from https://github.com/jss2a98aj/Baubles-Expanded/commit/93ceb1d99b85a1caee449f33ff97639866b1baed.

The issue affects only Linux and other case insensitive file systems.

**Temporary Solution from Author:**
> Copy Baubles.cfg and rename the copy baubles.cfg for the moment

This will be addressed shortly in a new update.
