### ISSUE TITLE
Inscribers generating in "veins" near Tuff underground.

### ISSUE THREAD

**Issue by CRF0806** [DrParadox7/Lost-Era-Modpack#83]
### Your Pack Version

1.6.2

### Type of Instance

Multiplayer

### Your Expectation

Went underground. Found tuff. Found a bunch of AE2 inscribers next to it.

### The Reality

This.

![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/116840497/7af7fd8c-862c-49c0-a86c-6927810f74e6)
![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/116840497/4c0d2b95-a4a5-4790-bb52-18b539c201ca)
![image](https://github.com/DrParadox7/Lost-Era-Modpack/assets/116840497/9eeab43d-4e92-4fbd-a26e-158030b80aab)

### Your Proposal

Can this just not happen please. I feel like I don't need to come up with a rationale as to why fully-blown machines shouldn't be spawning as ore veins underground.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
https://github.com/Roadhog360/Et-Futurum-Requiem/issues/341

**Comment by DrParadox7** [comment]
I've prepared a temporary solution which should address the problem until Et Futurum releases a fix.

**Comment by Roadhog360** [comment]
I'd also like to inform you the root cause of the issue has been found and will be addressed in the next Et Futurum Requiem update.
