### ISSUE TITLE
Failure to launch beacuse of DepLoader could not find baubles files but also when manually installed 

### ISSUE THREAD

**Issue by mrblon** [DrParadox7/Lost-Era-Modpack#84]
### Your Pack Version

1.6.2

### Type of Instance

Single Player

### Your Actions

When downloading the latest update, and loading up, the startup of the game opens up the DepLoader window with the prompt 

"CB's DepLoader was unable to download required library Baubles-1.7.10-1.0.1.10.jar Check your internet connection and try restarting or download it manually from https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar and put it in your mods folder"

But when downloading the relevant Baubles files, and manually putting it in the mods folder (I might have done this wrong, I opened up the folder by using the curseforge interface to get to the files for the "profile" with the modpack, where I dropped in the baubles files in the mods folder) the game still chrashes on startup. I have tried to reinstall the mod, update java to the latest edition, restarting my computer etc but this faliure continues to come up. 

### Crash Report

"Exit code 1"
[ClientLogs.txt](https://github.com/DrParadox7/Lost-Era-Modpack/files/12774360/ClientLogs.txt)
[latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/12774361/latest.log)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by mrblon** [comment]
Also thank you for all your work on the modpack, it is otherwise excellent and a great mod!

**Comment by DrParadox7** [comment]
Yeah, this is not a Bauble issue but an installation issue.
All your mods are not downloaded but still showing:
```[11:26:49] [main/ERROR]: Unable to read the jar file alreadydecoratingfix-1.0a.jar - ignoring
java.util.zip.ZipException: zip file is empty```

Either the installation has been forcefully killed or you have a firewall/antivirus preventing mods from being downloaded

**Comment by DrParadox7** [comment]
Closed from inactivity
