### ISSUE TITLE
Error while downloading *MOD* (There was an issue writing to file)

### ISSUE THREAD

**Issue by LyonGalaxy** [DrParadox7/Lost-Era-Modpack#90]
### Type of Instance

Single Player

### Installation Target

Your Own Computer or Laptop

### Your Actions

Installing the modpack directly from SKLauncher

### Your Pack Version

1.6.3

### Required Logs

[latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/13309918/latest.log)

### Final Checklist

- [X] I have provided all the required logs.
- [X] I searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Update your java 8 version or use a non-cracked launcher.
We do not support pirated versions of MC
