### ISSUE TITLE
Nther Quartz Blocks have Multiple Recipe's 

### ISSUE THREAD

**Issue by AcaciaTheArcane** [DrParadox7/Lost-Era-Modpack#92]
### Your Pack Version

1.6.3

### Type of Instance

Multiplayer

### Your Expectation

Nether Quartz blocks have a recipe that requires 4 Quartz and another that requires 9

### The Reality

In an ME system it pulls the recipe for 9 with shift crafting instead of the 4 piece recipe 

### Your Proposal

Remove the crafting recipe for the 9 piece block recipe or change the recipe to swap back from the block to yield 9 and remove the 4 piece recipe 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Fixed in v1.6.4
