### ISSUE TITLE
Game crashes after the mandatory restart

### ISSUE THREAD

**Issue by LegitHistory** [DrParadox7/Lost-Era-Modpack#95]
### Your Pack Version

1.6.4

### Type of Instance

Single Player

### Your Actions

I restarted the game after it ordered me to at first launch

### Crash Report

[latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/13933028/latest.log)

### Final Checklist

- [X] I have provided all the required crash reports/logs.
- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by DrParadox7** [comment]
Looking into it.
I find it impossible to reproduce on 3 different systems. If you have additional information regarding your system that is uncommon do let us know.

**Comment by LegitHistory** [comment]
Weird, I tried running it again and it works normally without doing anything
