### ISSUE TITLE
Rendering bug - Rednet Cables from MineFactory Reloaded not rendering fully

### ISSUE THREAD

**Issue by Mihnea229** [DrParadox7/Lost-Era-Modpack#97]
### Your Pack Version

1.6.4

### Type of Instance

Single Player

### Your Expectation

I was trying to connect some rednet cables from Minefactory reloaded and i was expecting them to look like this: 
![2024-02-10_00 34 26](https://github.com/DrParadox7/Lost-Era-Modpack/assets/47253515/5604402a-0eca-4cf6-87cf-7ed16bbed2c7)

### The Reality

Instead, the cables look like this: 
![2024-02-10_00 30 59](https://github.com/DrParadox7/Lost-Era-Modpack/assets/47253515/d95f4f6d-8e0f-4dba-80dc-2342cc9d992f)

### Your Proposal

This bug occurs without Optifine too. I want this bug fixed  because it's really weird to work with them looking like that.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Mihnea229** [comment]
I have discovered that in earlier pack versions the bug is not present. Maybe a mod update broke some things?

**Comment by DrParadox7** [comment]
Fixed in 1.6.5
